from app import create_app, db
from app.models import Category, Product

app = create_app()

def add_products():
    with app.app_context():
        # Delete existing products
        Product.query.delete()
        db.session.commit()
        print("All existing products deleted.")

        # Update categories
        categories = {
            'Whey Protein Concentrate': Category.query.filter_by(name='Whey Protein Concentrate').first() or Category(name='Whey Protein Concentrate'),
            'Whey Protein Isolate': Category.query.filter_by(name='Whey Protein Isolate').first() or Category(name='Whey Protein Isolate'),
            'Hydrolyzed Whey Protein': Category.query.filter_by(name='Hydrolyzed Whey Protein').first() or Category(name='Hydrolyzed Whey Protein'),
            'Pea Protein': Category.query.filter_by(name='Pea Protein').first() or Category(name='Pea Protein'),
            'Vegan Protein Blend': Category.query.filter_by(name='Vegan Protein Blend').first() or Category(name='Vegan Protein Blend'),
            'Protein Blend': Category.query.filter_by(name='Protein Blend').first() or Category(name='Protein Blend'),
            'Collagen Protein': Category.query.filter_by(name='Collagen Protein').first() or Category(name='Collagen Protein'),
            'Ready-to-Drink Protein': Category.query.filter_by(name='Ready-to-Drink Protein').first() or Category(name='Ready-to-Drink Protein'),
            'Vegan Protein': Category.query.filter_by(name='Vegan Protein').first() or Category(name='Vegan Protein'),
        }

        for category in categories.values():
            if category.id is None:
                db.session.add(category)
        db.session.commit()

        # Add products

        products = [
    {
        'name': 'Optimum Nutrition Gold Standard Whey',
        'brand': 'Optimum Nutrition',
        'type': 'Whey Protein Isolate',
        'flavor': 'Double Rich Chocolate',
        'ingredients': 'Whey Protein Isolate, Cocoa, Natural Flavors, Lecithin, Sucralose',
        'protein_per_serving': 24.0,
        'calories': 120,
        'sugar': 1.0,
        'carbohydrates': 3.0,
        'fats': 1.0,
        'saturated_fats': 0.5,
        'cholesterol': 30.0,
        'sodium': 130.0,
        'dietary_fiber': 1.0,
        'price': 29.99,
        'serving_size': '30g',
        'servings_per_container': 73,
        'flavors': ['Double Rich Chocolate', 'Vanilla Ice Cream', 'Strawberry Banana'],
        'allergens': 'Milk, Soy',
        'description': 'Best-selling whey protein with a great taste and high protein content.',
        'source': 'https://www.optimumnutrition.com',
    },
    {
        'name': 'Dymatize ISO100',
        'brand': 'Dymatize',
        'type': 'Hydrolyzed Whey Protein',
        'flavor': 'Gourmet Vanilla',
        'ingredients': 'Hydrolyzed Whey Protein Isolate, Natural and Artificial Flavors, Soy Lecithin, Salt, Sucralose, Steviol Glycosides',
        'protein_per_serving': 25.0,
        'calories': 110,
        'sugar': 0.0,
        'carbohydrates': 2.0,
        'fats': 0.5,
        'saturated_fats': 0.0,
        'cholesterol': 10.0,
        'sodium': 160.0,
        'dietary_fiber': 0.0,
        'price': 34.99,
        'serving_size': '28g',
        'servings_per_container': 81,
        'flavors': ['Gourmet Vanilla', 'Chocolate Peanut Butter', 'Birthday Cake'],
        'allergens': 'Milk, Soy',
        'description': 'Fast-digesting, hydrolyzed protein powder ideal for muscle recovery.',
        'source': 'https://www.dymatize.com',
    },
    {
        'name': 'Garden of Life Organic Plant Protein',
        'brand': 'Garden of Life',
        'type': 'Vegan Protein Blend',
        'flavor': 'Smooth Vanilla',
        'ingredients': 'Pea Protein, Organic Sprouted Amaranth, Organic Sprouted Quinoa, Organic MCT Powder, Natural Vanilla Flavor',
        'protein_per_serving': 15.0,
        'calories': 100,
        'sugar': 0.0,
        'carbohydrates': 3.0,
        'fats': 1.0,
        'saturated_fats': 0.5,
        'cholesterol': 0.0,
        'sodium': 160.0,
        'dietary_fiber': 2.0,
        'price': 27.99,
        'serving_size': '23g',
        'servings_per_container': 20,
        'flavors': ['Smooth Vanilla', 'Chocolate Cacao', 'Unflavored'],
        'allergens': 'None',
        'description': 'Certified organic plant protein blend for those seeking a vegan option.',
        'source': 'https://www.gardenoflife.com',
    },
    {
        'name': 'MusclePharm Combat Protein Powder',
        'brand': 'MusclePharm',
        'type': 'Protein Blend',
        'flavor': 'Cookies N\' Cream',
        'ingredients': 'Whey Protein Isolate, Whey Protein Concentrate, Egg Albumin, Micellar Casein, Natural and Artificial Flavors',
        'protein_per_serving': 25.0,
        'calories': 140,
        'sugar': 2.0,
        'carbohydrates': 5.0,
        'fats': 1.5,
        'saturated_fats': 1.0,
        'cholesterol': 35.0,
        'sodium': 150.0,
        'dietary_fiber': 1.0,
        'price': 26.99,
        'serving_size': '32g',
        'servings_per_container': 52,
        'flavors': ['Cookies N\' Cream', 'Chocolate Milk', 'Vanilla'],
        'allergens': 'Milk, Egg, Soy',
        'description': 'Multi-source protein blend designed for muscle growth and recovery.',
        'source': 'https://www.musclepharm.com',
    },
    {
        'name': 'Vega Sport Premium Protein',
        'brand': 'Vega',
        'type': 'Vegan Protein Blend',
        'flavor': 'Chocolate',
        'ingredients': 'Pea Protein, Pumpkin Seed Protein, Organic Sunflower Seed Protein, Alfalfa Protein, Cocoa, Natural Flavors',
        'protein_per_serving': 30.0,
        'calories': 160,
        'sugar': 2.0,
        'carbohydrates': 6.0,
        'fats': 3.0,
        'saturated_fats': 0.5,
        'cholesterol': 0.0,
        'sodium': 390.0,
        'dietary_fiber': 2.0,
        'price': 39.99,
        'serving_size': '41g',
        'servings_per_container': 20,
        'flavors': ['Chocolate', 'Vanilla', 'Mocha'],
        'allergens': 'None',
        'description': 'High-protein blend for athletes looking for a vegan recovery option.',
        'source': 'https://www.myvega.com',
    },
    {
        'name': 'Orgain Organic Protein',
        'brand': 'Orgain',
        'type': 'Vegan Protein Blend',
        'flavor': 'Creamy Chocolate Fudge',
        'ingredients': 'Organic Pea Protein, Organic Brown Rice Protein, Organic Chia Seed, Organic Cocoa, Organic Acacia, Natural Flavors',
        'protein_per_serving': 21.0,
        'calories': 150,
        'sugar': 0.0,
        'carbohydrates': 15.0,
        'fats': 4.0,
        'saturated_fats': 0.5,
        'cholesterol': 0.0,
        'sodium': 230.0,
        'dietary_fiber': 5.0,
        'price': 27.99,
        'serving_size': '46g',
        'servings_per_container': 20,
        'flavors': ['Creamy Chocolate Fudge', 'Vanilla Bean', 'Peanut Butter'],
        'allergens': 'None',
        'description': 'Organic plant-based protein powder with added fiber and no added sugar.',
        'source': 'https://www.orgain.com',
    },
    {
        'name': 'Naked Whey',
        'brand': 'Naked Nutrition',
        'type': 'Whey Protein Concentrate',
        'flavor': 'Unflavored',
        'ingredients': '100% Grass-Fed Whey Protein Concentrate',
        'protein_per_serving': 25.0,
        'calories': 120,
        'sugar': 2.0,
        'carbohydrates': 3.0,
        'fats': 2.5,
        'saturated_fats': 1.5,
        'cholesterol': 55.0,
        'sodium': 45.0,
        'dietary_fiber': 0.0,
        'price': 89.99,
        'serving_size': '30g',
        'servings_per_container': 76,
        'flavors': ['Unflavored'],
        'allergens': 'Milk',
        'description': 'Pure grass-fed whey protein with no artificial ingredients.',
        'source': 'https://www.nakednutrition.com',
    },
        {
        'name': 'Sunwarrior Classic Plus',
        'brand': 'Sunwarrior',
        'type': 'Vegan Protein Blend',
        'flavor': 'Vanilla',
        'ingredients': 'Organic Pea Protein, Organic Brown Rice Protein, Organic Quinoa, Organic Chia Seed, Organic Amaranth, Natural Vanilla Flavor',
        'protein_per_serving': 18.0,
        'calories': 100,
        'sugar': 0.0,
        'carbohydrates': 4.0,
        'fats': 2.0,
        'saturated_fats': 0.5,
        'cholesterol': 0.0,
        'sodium': 110.0,
        'dietary_fiber': 1.0,
        'price': 42.99,
        'serving_size': '25g',
        'servings_per_container': 30,
        'flavors': ['Vanilla', 'Chocolate', 'Natural'],
        'allergens': 'None',
        'description': 'Organic plant-based protein blend with a smooth taste and texture.',
        'source': 'https://www.sunwarrior.com',
    },
    {
        'name': 'BSN Syntha-6',
        'brand': 'BSN',
        'type': 'Protein Blend',
        'flavor': 'Strawberry Milkshake',
        'ingredients': 'Whey Protein Concentrate, Milk Protein Isolate, Whey Protein Isolate, Micellar Casein, Egg Albumin, Glutamine Peptides',
        'protein_per_serving': 22.0,
        'calories': 200,
        'sugar': 2.0,
        'carbohydrates': 15.0,
        'fats': 6.0,
        'saturated_fats': 2.0,
        'cholesterol': 70.0,
        'sodium': 160.0,
        'dietary_fiber': 5.0,
        'price': 49.99,
        'serving_size': '47g',
        'servings_per_container': 48,
        'flavors': ['Strawberry Milkshake', 'Chocolate Milkshake', 'Vanilla Ice Cream'],
        'allergens': 'Milk, Egg, Soy',
        'description': 'Delicious protein blend offering a sustained release of amino acids.',
        'source': 'https://www.gobsn.com',
    },
    {
        'name': 'Kaged Muscle Micropure Whey Protein Isolate',
        'brand': 'Kaged Muscle',
        'type': 'Whey Protein Isolate',
        'flavor': 'Chocolate',
        'ingredients': 'Whey Protein Isolate, Cocoa Powder, Natural Flavors, Salt, Stevia Leaf Extract, Sucralose',
        'protein_per_serving': 25.0,
        'calories': 110,
        'sugar': 0.0,
        'carbohydrates': 2.0,
        'fats': 0.5,
        'saturated_fats': 0.0,
        'cholesterol': 5.0,
        'sodium': 45.0,
        'dietary_fiber': 0.0,
        'price': 44.99,
        'serving_size': '32g',
        'servings_per_container': 36,
        'flavors': ['Chocolate', 'Vanilla'],
        'allergens': 'Milk, Soy',
        'description': 'Microfiltered whey protein isolate for fast absorption and muscle growth.',
        'source': 'https://www.kagedmuscle.com',
    },
    {
        'name': 'Isopure Zero Carb',
        'brand': 'Isopure',
        'type': 'Whey Protein Isolate',
        'flavor': 'Cookies and Cream',
        'ingredients': 'Whey Protein Isolate, Cocoa Powder, Natural Flavors, Salt, Soy Lecithin, Sucralose',
        'protein_per_serving': 25.0,
        'calories': 100,
        'sugar': 0.0,
        'carbohydrates': 0.0,
        'fats': 0.0,
        'saturated_fats': 0.0,
        'cholesterol': 10.0,
        'sodium': 160.0,
        'dietary_fiber': 0.0,
        'price': 49.99,
        'serving_size': '31g',
        'servings_per_container': 44,
        'flavors': ['Cookies and Cream', 'Chocolate', 'Vanilla'],
        'allergens': 'Milk, Soy',
        'description': 'Zero carb protein isolate ideal for low-carb or ketogenic diets.',
        'source': 'https://www.theisopurecompany.com',
    },
    {
        'name': 'Orgain Organic Protein + Superfoods',
        'brand': 'Orgain',
        'type': 'Vegan Protein Blend',
        'flavor': 'Berry',
        'ingredients': 'Organic Pea Protein, Organic Chia Seeds, Organic Brown Rice Protein, Organic Acacia, Organic Moringa, Organic Spinach, Organic Kale, Organic Beets',
        'protein_per_serving': 21.0,
        'calories': 170,
        'sugar': 1.0,
        'carbohydrates': 15.0,
        'fats': 5.0,
        'saturated_fats': 0.5,
        'cholesterol': 0.0,
        'sodium': 250.0,
        'dietary_fiber': 7.0,
        'price': 31.99,
        'serving_size': '51g',
        'servings_per_container': 20,
        'flavors': ['Berry', 'Vanilla Bean', 'Chocolate'],
        'allergens': 'None',
        'description': 'Vegan protein blend with added superfoods for enhanced nutrition.',
        'source': 'https://www.orgain.com',
    },
    {
        'name': 'Quest Protein Powder',
        'brand': 'Quest Nutrition',
        'type': 'Whey Protein Isolate',
        'flavor': 'Cookies & Cream',
        'ingredients': 'Whey Protein Isolate, Micellar Casein, Natural Flavors, Sunflower Lecithin, Cellulose Gum, Steviol Glycosides, Salt',
        'protein_per_serving': 24.0,
        'calories': 110,
        'sugar': 1.0,
        'carbohydrates': 2.0,
        'fats': 1.5,
        'saturated_fats': 0.5,
        'cholesterol': 20.0,
        'sodium': 160.0,
        'dietary_fiber': 1.0,
        'price': 29.99,
        'serving_size': '31g',
        'servings_per_container': 45,
        'flavors': ['Cookies & Cream', 'Chocolate Milkshake', 'Vanilla Milkshake'],
        'allergens': 'Milk',
        'description': 'Delicious whey protein isolate with low carbs and sugar.',
        'source': 'https://www.questnutrition.com',
    },
    {
        'name': 'Vega Protein & Greens',
        'brand': 'Vega',
        'type': 'Vegan Protein Blend',
        'flavor': 'Vanilla',
        'ingredients': 'Pea Protein, Brown Rice Protein, Sacha Inchi Protein, Organic Spinach Powder, Organic Kale Powder, Natural Vanilla Flavor',
        'protein_per_serving': 20.0,
        'calories': 110,
        'sugar': 1.0,
        'carbohydrates': 6.0,
        'fats': 2.0,
        'saturated_fats': 0.5,
        'cholesterol': 0.0,
        'sodium': 230.0,
        'dietary_fiber': 2.0,
        'price': 32.99,
        'serving_size': '25g',
        'servings_per_container': 22,
        'flavors': ['Vanilla', 'Chocolate', 'Berry'],
        'allergens': 'None',
        'description': 'Vegan protein with added greens for a nutrient boost.',
        'source': 'https://www.myvega.com',
    },
        {
        'name': 'Bodylogix Natural Whey',
        'brand': 'Bodylogix',
        'type': 'Whey Protein Isolate',
        'flavor': 'Chocolate',
        'ingredients': 'Whey Protein Isolate, Natural Flavors, Sunflower Lecithin, Stevia Leaf Extract, Cocoa Powder',
        'protein_per_serving': 24.0,
        'calories': 120,
        'sugar': 2.0,
        'carbohydrates': 3.0,
        'fats': 1.0,
        'saturated_fats': 0.5,
        'cholesterol': 10.0,
        'sodium': 110.0,
        'dietary_fiber': 1.0,
        'price': 59.99,
        'serving_size': '31g',
        'servings_per_container': 60,
        'flavors': ['Chocolate', 'Vanilla'],
        'allergens': 'Milk, Soy',
        'description': 'Natural whey protein with no artificial flavors, colors, or sweeteners.',
        'source': 'https://www.bodylogix.com',
    },
    {
        'name': 'Legion Whey+',
        'brand': 'Legion Athletics',
        'type': 'Whey Protein Isolate',
        'flavor': 'Mocha Cappuccino',
        'ingredients': 'Whey Protein Isolate, Natural Flavors, Cocoa Powder, Stevia Leaf Extract, Sea Salt',
        'protein_per_serving': 22.0,
        'calories': 100,
        'sugar': 0.0,
        'carbohydrates': 3.0,
        'fats': 0.0,
        'saturated_fats': 0.0,
        'cholesterol': 5.0,
        'sodium': 100.0,
        'dietary_fiber': 1.0,
        'price': 49.99,
        'serving_size': '25g',
        'servings_per_container': 28,
        'flavors': ['Mocha Cappuccino', 'Chocolate', 'Vanilla'],
        'allergens': 'Milk',
        'description': 'Cold-processed, non-GMO whey isolate with natural sweeteners and flavors.',
        'source': 'https://www.legionathletics.com',
    },
    {
        'name': 'Dymatize ISO100',
        'brand': 'Dymatize',
        'type': 'Hydrolyzed Whey Protein Isolate',
        'flavor': 'Birthday Cake',
        'ingredients': 'Hydrolyzed Whey Protein Isolate, Whey Protein Isolate, Natural and Artificial Flavors, Salt, Sucralose',
        'protein_per_serving': 25.0,
        'calories': 110,
        'sugar': 1.0,
        'carbohydrates': 2.0,
        'fats': 0.5,
        'saturated_fats': 0.0,
        'cholesterol': 10.0,
        'sodium': 160.0,
        'dietary_fiber': 0.0,
        'price': 64.99,
        'serving_size': '30g',
        'servings_per_container': 73,
        'flavors': ['Birthday Cake', 'Chocolate', 'Vanilla'],
        'allergens': 'Milk, Soy',
        'description': 'Fast-digesting hydrolyzed whey isolate perfect for post-workout recovery.',
        'source': 'https://www.dymatize.com',
    },
    {
        'name': 'Nutiva Organic Plant Protein',
        'brand': 'Nutiva',
        'type': 'Vegan Protein Blend',
        'flavor': 'Vanilla',
        'ingredients': 'Organic Pea Protein, Organic Pumpkin Seed Protein, Organic Sunflower Seed Protein, Organic Hemp Protein, Organic Coconut Sugar, Organic Vanilla Flavor',
        'protein_per_serving': 21.0,
        'calories': 120,
        'sugar': 2.0,
        'carbohydrates': 7.0,
        'fats': 3.0,
        'saturated_fats': 1.0,
        'cholesterol': 0.0,
        'sodium': 200.0,
        'dietary_fiber': 5.0,
        'price': 34.99,
        'serving_size': '30g',
        'servings_per_container': 30,
        'flavors': ['Vanilla', 'Chocolate'],
        'allergens': 'None',
        'description': 'Organic plant-based protein with a blend of pea, pumpkin, and sunflower seed proteins.',
        'source': 'https://www.nutiva.com',
    },
    {
        'name': 'Evolve Plant-Based Protein',
        'brand': 'Evolve',
        'type': 'Vegan Protein Blend',
        'flavor': 'Classic Chocolate',
        'ingredients': 'Pea Protein, Cocoa Powder, Natural Flavors, Stevia Leaf Extract, Sea Salt, Guar Gum',
        'protein_per_serving': 20.0,
        'calories': 160,
        'sugar': 1.0,
        'carbohydrates': 10.0,
        'fats': 3.5,
        'saturated_fats': 0.0,
        'cholesterol': 0.0,
        'sodium': 200.0,
        'dietary_fiber': 10.0,
        'price': 29.99,
        'serving_size': '36g',
        'servings_per_container': 30,
        'flavors': ['Classic Chocolate', 'Vanilla'],
        'allergens': 'None',
        'description': 'Plant-based protein with a simple ingredient list and high fiber content.',
        'source': 'https://www.drinkevolve.com',
    },
    {
        'name': 'Muscletech Nitro-Tech',
        'brand': 'Muscletech',
        'type': 'Whey Protein Isolate',
        'flavor': 'Double Rich Chocolate',
        'ingredients': 'Whey Protein Isolate, Whey Peptides, Cocoa Powder, Natural and Artificial Flavors, Salt, Sucralose',
        'protein_per_serving': 30.0,
        'calories': 160,
        'sugar': 2.0,
        'carbohydrates': 4.0,
        'fats': 2.5,
        'saturated_fats': 1.5,
        'cholesterol': 70.0,
        'sodium': 150.0,
        'dietary_fiber': 1.0,
        'price': 69.99,
        'serving_size': '44g',
        'servings_per_container': 40,
        'flavors': ['Double Rich Chocolate', 'Vanilla', 'Strawberry'],
        'allergens': 'Milk, Soy',
        'description': 'Advanced protein powder with added creatine and BCAAs for enhanced performance.',
        'source': 'https://www.muscletech.com',
    },
    {
        'name': 'Naked Whey',
        'brand': 'Naked Nutrition',
        'type': 'Whey Protein Concentrate',
        'flavor': 'Unflavored',
        'ingredients': 'Whey Protein Concentrate',
        'protein_per_serving': 25.0,
        'calories': 120,
        'sugar': 2.0,
        'carbohydrates': 3.0,
        'fats': 1.0,
        'saturated_fats': 0.5,
        'cholesterol': 15.0,
        'sodium': 45.0,
        'dietary_fiber': 0.0,
        'price': 89.99,
        'serving_size': '30g',
        'servings_per_container': 76,
        'flavors': ['Unflavored'],
        'allergens': 'Milk',
        'description': '100% pure whey protein concentrate with no additives, sourced from grass-fed cows.',
        'source': 'https://www.nakednutrition.com',
    },
    {
        'name': 'Orgain Organic Protein',
        'brand': 'Orgain',
        'type': 'Vegan Protein Blend',
        'flavor': 'Chocolate Fudge',
        'ingredients': 'Organic Pea Protein, Organic Brown Rice Protein, Organic Chia Seeds, Organic Cocoa, Organic Erythritol, Organic Stevia',
        'protein_per_serving': 21.0,
        'calories': 150,
        'sugar': 0.0,
        'carbohydrates': 15.0,
        'fats': 4.0,
        'saturated_fats': 0.5,
        'cholesterol': 0.0,
        'sodium': 250.0,
        'dietary_fiber': 6.0,
        'price': 39.99,
        'serving_size': '46g',
        'servings_per_container': 20,
        'flavors': ['Chocolate Fudge', 'Vanilla'],
        'allergens': 'None',
        'description': 'USDA organic protein blend perfect for vegans, with a delicious chocolate fudge flavor.',
        'source':'https://www.orgain.com'
    },
    {
        'name': 'Ghost Whey Protein',
        'brand': 'Ghost',
        'type': 'Whey Protein Blend',
        'flavor': 'Cereal Milk',
        'ingredients': 'Whey Protein Isolate, Whey Protein Concentrate, Hydrolyzed Whey Protein Isolate, Natural and Artificial Flavors, Sucralose, Enzymes',
        'protein_per_serving': 25.0,
        'calories': 130,
        'sugar': 2.0,
        'carbohydrates': 4.0,
        'fats': 1.5,
        'saturated_fats': 1.0,
        'cholesterol': 40.0,
        'sodium': 150.0,
        'dietary_fiber': 0.0,
        'price': 44.99,
        'serving_size': '35g',
        'servings_per_container': 26,
        'flavors': ['Cereal Milk', 'Fruity Cereal', 'Peanut Butter Cereal Milk'],
        'allergens': 'Milk',
        'description': 'Whey protein blend with fun and nostalgic cereal flavors, great for post-workout.',
        'source': 'https://www.ghostlifestyle.com',
    },
    {
        'name': 'RSP AvoCollagen',
        'brand': 'RSP Nutrition',
        'type': 'Collagen Protein',
        'flavor': 'Vanilla',
        'ingredients': 'Hydrolyzed Bovine Collagen Peptides, Avocado Oil Powder, Natural Flavors, Stevia Leaf Extract',
        'protein_per_serving': 10.0,
        'calories': 100,
        'sugar': 0.0,
        'carbohydrates': 3.0,
        'fats': 5.0,
        'saturated_fats': 1.0,
        'cholesterol': 0.0,
        'sodium': 100.0,
        'dietary_fiber': 0.0,
        'price': 34.99,
        'serving_size': '12g',
        'servings_per_container': 30,
        'flavors': ['Vanilla'],
        'allergens': 'None',
        'description': 'Collagen protein combined with healthy fats from avocado oil for skin and joint support.',
        'source': 'https://www.rspnutrition.com',
    },
    {
        'name': 'Ascent Native Fuel Whey',
        'brand': 'Ascent',
        'type': 'Whey Protein Isolate',
        'flavor': 'Lemon Sorbet',
        'ingredients': 'Whey Protein Isolate, Natural Flavors, Stevia Leaf Extract, Lemon Juice Powder',
        'protein_per_serving': 25.0,
        'calories': 120,
        'sugar': 1.0,
        'carbohydrates': 2.0,
        'fats': 1.0,
        'saturated_fats': 0.5,
        'cholesterol': 15.0,
        'sodium': 250.0,
        'dietary_fiber': 0.0,
        'price': 44.99,
        'serving_size': '32g',
        'servings_per_container': 30,
        'flavors': ['Lemon Sorbet', 'Chocolate', 'Vanilla'],
        'allergens': 'Milk',
        'description': 'Clean and pure whey protein isolate with a refreshing lemon sorbet flavor.',
        'source': 'https://www.ascentprotein.com',
    },
    {
        'name': 'ProMix Grass-Fed Whey',
        'brand': 'ProMix Nutrition',
        'type': 'Whey Protein Concentrate',
        'flavor': 'Chocolate',
        'ingredients': 'Grass-Fed Whey Protein Concentrate, Organic Cocoa Powder, Non-GMO Sunflower Lecithin',
        'protein_per_serving': 25.0,
        'calories': 130,
        'sugar': 1.0,
        'carbohydrates': 3.0,
        'fats': 2.0,
        'saturated_fats': 1.0,
        'cholesterol': 60.0,
        'sodium': 40.0,
        'dietary_fiber': 0.0,
        'price': 49.99,
        'serving_size': '32g',
        'servings_per_container': 62,
        'flavors': ['Chocolate', 'Unflavored'],
        'allergens': 'Milk',
        'description': 'Grass-fed whey protein concentrate with no artificial ingredients or sweeteners.',
        'source': 'https://www.promixnutrition.com',
    },
    {
        'name': 'Pea Protein by Now Sports',
        'brand': 'Now Sports',
        'type': 'Vegan Protein',
        'flavor': 'Unflavored',
        'ingredients': 'Pea Protein Isolate',
        'protein_per_serving': 24.0,
        'calories': 120,
        'sugar': 0.0,
        'carbohydrates': 1.0,
        'fats': 2.0,
        'saturated_fats': 0.0,
        'cholesterol': 0.0,
        'sodium': 230.0,
        'dietary_fiber': 0.0,
        'price': 26.99,
        'serving_size': '33g',
        'servings_per_container': 21,
        'flavors': ['Unflavored'],
        'allergens': 'None',
        'description': 'Pure pea protein isolate for vegetarians, vegans, and those with dietary restrictions.',
        'source': 'https://www.nowfoods.com',
    },
    {
        'name': 'Sunwarrior Warrior Blend',
        'brand': 'Sunwarrior',
        'type': 'Vegan Protein Blend',
        'flavor': 'Mocha',
        'ingredients': 'Pea Protein, Hemp Protein, Goji Berry, Coconut MCTs, Natural Mocha Flavor, Stevia',
        'protein_per_serving': 25.0,
        'calories': 100,
        'sugar': 0.0,
        'carbohydrates': 3.0,
        'fats': 2.0,
        'saturated_fats': 1.0,
        'cholesterol': 0.0,
        'sodium': 300.0,
        'dietary_fiber': 1.0,
        'price': 39.99,
        'serving_size': '25g',
        'servings_per_container': 30,
        'flavors': ['Mocha', 'Chocolate', 'Vanilla'],
        'allergens': 'Coconut',
        'description': 'Unique vegan blend with a mix of proteins and antioxidants for muscle recovery.',
        'source': 'https://www.sunwarrior.com',
    },
    {
        'name': 'Alani Nu Whey Protein',
        'brand': 'Alani Nu',
        'type': 'Whey Protein Isolate',
        'flavor': 'Munchies',
        'ingredients': 'Whey Protein Isolate, Whey Protein Concentrate, Natural and Artificial Flavors, Sucralose',
        'protein_per_serving': 23.0,
        'calories': 110,
        'sugar': 1.0,
        'carbohydrates': 3.0,
        'fats': 1.5,
        'saturated_fats': 1.0,
        'cholesterol': 15.0,
        'sodium': 180.0,
        'dietary_fiber': 0.0,
        'price': 44.99,
        'serving_size': '31g',
        'servings_per_container': 30,
        'flavors': ['Munchies', 'Fruity Cereal', 'Confetti Cake'],
        'allergens': 'Milk, Soy',
        'description': 'Fun and flavorful whey protein with unique taste profiles and high protein content.',
        'source': 'https://www.alaninu.com',
    },
    {
        'name': 'MyProtein Impact Whey',
        'brand': 'MyProtein',
        'type': 'Whey Protein Concentrate',
        'flavor': 'Natural Vanilla',
        'ingredients': 'Whey Protein Concentrate, Natural Vanilla Flavor, Soy Lecithin, Stevia',
        'protein_per_serving': 21.0,
        'calories': 103,
        'sugar': 1.0,
        'carbohydrates': 2.0,
        'fats': 1.9,
        'saturated_fats': 1.0,
        'cholesterol': 0.0,
        'sodium': 100.0,
        'dietary_fiber': 0.0,
        'price': 29.99,
        'serving_size': '25g',
        'servings_per_container': 40,
        'flavors': ['Natural Vanilla', 'Chocolate', 'Strawberry'],
        'allergens': 'Milk, Soy',
        'description': 'Affordable and high-quality whey protein concentrate available in multiple flavors.',
        'source': 'https://www.myprotein.com',
    },
    {
        'name': 'Naked Nutrition Whey',
        'brand': 'Naked Nutrition',
        'type': 'Whey Protein Concentrate',
        'flavor': 'Unflavored',
        'ingredients': 'Grass-Fed Whey Protein Concentrate',
        'protein_per_serving': 25.0,
        'calories': 120,
        'sugar': 2.0,
        'carbohydrates': 3.0,
        'fats': 2.0,
        'saturated_fats': 1.0,
        'cholesterol': 55.0,
        'sodium': 45.0,
        'dietary_fiber': 0.0,
        'price': 89.99,
        'serving_size': '30g',
        'servings_per_container': 76,
        'flavors': ['Unflavored'],
        'allergens': 'Milk',
        'description': 'Pure, grass-fed whey protein with no additives, artificial sweeteners, or flavors.',
        'source': 'https://www.nakednutrition.com',
    },
    {
        'name': 'Legion Whey+',
        'brand': 'Legion Athletics',
        'type': 'Whey Protein Isolate',
        'flavor': 'Dutch Chocolate',
        'ingredients': 'Whey Protein Isolate, Cocoa Powder, Natural Flavors, Stevia Leaf Extract, Sea Salt',
        'protein_per_serving': 22.0,
        'calories': 100,
        'sugar': 0.0,
        'carbohydrates': 3.0,
        'fats': 1.0,
        'saturated_fats': 0.5,
        'cholesterol': 5.0,
        'sodium': 80.0,
        'dietary_fiber': 0.0,
        'price': 49.99,
        'serving_size': '28g',
        'servings_per_container': 30,
        'flavors': ['Dutch Chocolate', 'Cinnamon Cereal', 'Salted Caramel'],
        'allergens': 'Milk',
        'description': 'Grass-fed whey protein isolate with natural ingredients and no artificial sweeteners.',
        'source': 'https://www.legionathletics.com',
    },
    {
        'name': 'Iconic Protein Drink',
        'brand': 'Iconic Protein',
        'type': 'Ready-to-Drink Protein Shake',
        'flavor': 'Café Latte',
        'ingredients': 'Milk Protein Isolate, Cocoa Powder, Coffee Extract, Natural Flavors, Sea Salt, Monk Fruit Extract, Organic Agave Inulin',
        'protein_per_serving': 20.0,
        'calories': 140,
        'sugar': 3.0,
        'carbohydrates': 8.0,
        'fats': 2.5,
        'saturated_fats': 1.5,
        'cholesterol': 10.0,
        'sodium': 180.0,
        'dietary_fiber': 4.0,
        'price': 39.99,
        'serving_size': '11.5oz',
        'servings_per_container': 12,
        'flavors': ['Café Latte', 'Vanilla Bean', 'Chocolate Truffle'],
        'allergens': 'Milk',
        'description': 'Ready-to-drink protein shake with caffeine boost and high protein content.',
        'source': 'https://www.drinkiconic.com',
    },
    {
        'name': 'Quest Protein Powder',
        'brand': 'Quest Nutrition',
        'type': 'Whey Protein Blend',
        'flavor': 'Cookies & Cream',
        'ingredients': 'Whey Protein Isolate, Micellar Casein, Natural Flavors, Sunflower Lecithin, Sucralose, Stevia',
        'protein_per_serving': 24.0,
        'calories': 110,
        'sugar': 1.0,
        'carbohydrates': 3.0,
        'fats': 0.5,
        'saturated_fats': 0.0,
        'cholesterol': 15.0,
        'sodium': 170.0,
        'dietary_fiber': 1.0,
        'price': 29.99,
        'serving_size': '31g',
        'servings_per_container': 45,
        'flavors': ['Cookies & Cream', 'Chocolate Milkshake', 'Vanilla Milkshake'],
        'allergens': 'Milk',
        'description': 'High-protein, low-carb whey protein blend with delicious dessert-inspired flavors.',
        'source': 'https://www.questnutrition.com',
    },
    {
        'name': 'Isopure Zero Carb',
        'brand': 'Isopure',
        'type': 'Whey Protein Isolate',
        'flavor': 'Alpine Punch',
        'ingredients': 'Whey Protein Isolate, Natural and Artificial Flavors, Sucralose, Red Beet Powder',
        'protein_per_serving': 25.0,
        'calories': 100,
        'sugar': 0.0,
        'carbohydrates': 0.0,
        'fats': 0.5,
        'saturated_fats': 0.0,
        'cholesterol': 5.0,
        'sodium': 160.0,
        'dietary_fiber': 0.0,
        'price': 49.99,
        'serving_size': '31g',
        'servings_per_container': 44,
        'flavors': ['Alpine Punch', 'Chocolate', 'Vanilla'],
        'allergens': 'Milk',
        'description': 'Zero carb whey protein isolate with a light and refreshing fruit punch flavor.',
        'source': 'https://www.theisopurecompany.com',
    },
    {
        'name': 'Owyn Vegan Protein Shake',
        'brand': 'Owyn',
        'type': 'Ready-to-Drink Vegan Protein Shake',
        'flavor': 'Dark Chocolate',
        'ingredients': 'Pea Protein, Pumpkin Seed Protein, Organic Flax Oil, Cocoa Powder, Monk Fruit Extract, Stevia',
        'protein_per_serving': 20.0,
        'calories': 180,
        'sugar': 4.0,
        'carbohydrates': 7.0,
        'fats': 5.0,
        'saturated_fats': 1.0,
        'cholesterol': 0.0,
        'sodium': 190.0,
        'dietary_fiber': 5.0,
        'price': 29.99,
        'serving_size': '12oz',
        'servings_per_container': 12,
        'flavors': ['Dark Chocolate', 'Vanilla', 'Cookies & Cream'],
        'allergens': 'None',
        'description': 'Plant-based protein shake with organic ingredients and no artificial sweeteners.',
        'source': 'https://www.liveowyn.com',
    },
    {
        'name': 'Cellucor COR-Performance Whey',
        'brand': 'Cellucor',
        'type': 'Whey Protein Isolate',
        'flavor': 'Molten Chocolate',
        'ingredients': 'Whey Protein Isolate, Whey Protein Concentrate, Cocoa Powder, Natural and Artificial Flavors, Sucralose, Acesulfame Potassium',
        'protein_per_serving': 24.0,
        'calories': 120,
        'sugar': 1.0,
        'carbohydrates': 4.0,
        'fats': 1.5,
        'saturated_fats': 1.0,
        'cholesterol': 35.0,
        'sodium': 150.0,
        'dietary_fiber': 0.0,
        'price': 39.99,
        'serving_size': '33g',
        'servings_per_container': 27,
        'flavors': ['Molten Chocolate', 'Cinnamon Swirl', 'Strawberry Milkshake'],
        'allergens': 'Milk, Soy',
        'description': 'Fast-digesting whey protein isolate for muscle recovery and building, available in tasty flavors.',
        'source': 'https://www.cellucor.com'
        },
    ]
        
        for product_data in products:
            category = None
            product_type = product_data['type'].lower()
            
            if 'ready-to-drink' in product_type:
                category = categories['Ready-to-Drink Protein']
            elif 'pea protein' in product_type:
                category = categories['Pea Protein']
            elif 'vegan protein blend' in product_type:
                category = categories['Vegan Protein Blend']
            elif 'vegan protein' in product_type:
                category = categories['Vegan Protein']
            else:
                for cat_name, cat_obj in categories.items():
                    if cat_name.lower() in product_type:
                        category = cat_obj
                        break
            
            if not category:
                print(f"Unknown category for product {product_data['name']} with type {product_data['type']}")
                continue

            product = Product(
                name=product_data['name'],
                brand=product_data['brand'],
                type=product_data['type'],
                flavor=product_data['flavor'],
                ingredients=product_data['ingredients'],
                protein_per_serving=product_data['protein_per_serving'],
                calories=product_data['calories'],
                sugar=product_data['sugar'],
                carbohydrates=product_data['carbohydrates'],
                fats=product_data['fats'],
                saturated_fats=product_data['saturated_fats'],
                cholesterol=product_data['cholesterol'],
                sodium=product_data['sodium'],
                dietary_fiber=product_data['dietary_fiber'],
                price=product_data['price'],
                serving_size=product_data['serving_size'],
                servings_per_container=product_data['servings_per_container'],
                flavors=', '.join(product_data['flavors']),
                allergens=product_data['allergens'],
                description=product_data['description'],
                source=product_data['source'],
                category=category
            )
            db.session.add(product)

        db.session.commit()
        print("Products added successfully!")

        # Verify products were added
        print(f"Total products: {Product.query.count()}")
        print(f"Total categories: {Category.query.count()}")
        for category in Category.query.all():
            print(f"{category.name}: {len(category.products)} products")

if __name__ == "__main__":
    add_products()
    
    
#     Summary
# Purpose: Clears existing products and adds a predefined set of products and categories to the database.
# Key Steps:
# Remove existing products.
# Ensure categories exist or add them.
# Add new products with proper categorization.
# Verify the addition of products and categories.
