"""Change serving_size to string

Revision ID: 5afa0378f2c8
Revises: 8d7514606332
Create Date: 2024-08-30 21:23:07.938054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afa0378f2c8'
down_revision = '8d7514606332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('serving_size',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('serving_size',
               existing_type=sa.String(length=10),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
