"""added chloretorl

Revision ID: 831d95c4f65c
Revises: 5afa0378f2c8
Create Date: 2024-09-03 18:33:46.456539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831d95c4f65c'
down_revision = '5afa0378f2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saturated_fats', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dietary_fiber', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('dietary_fiber')
        batch_op.drop_column('sodium')
        batch_op.drop_column('cholesterol')
        batch_op.drop_column('saturated_fats')

    # ### end Alembic commands ###
