"""Add flavor field to Product model

Revision ID: 8d7514606332
Revises: dad0fa1e6f6f
Create Date: 2024-08-26 13:23:55.903284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7514606332'
down_revision = 'dad0fa1e6f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavor', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('flavor')

    # ### end Alembic commands ###
